Address Foodcritic rule FC086
americanhanko/vsts-agent-macos-cookbook pull request #6
Opened 2019-01-10 00:56 UTC by americanhanko

## This PR

Addresses Foodcritic rule [FC086: Use databag helper methods to load data bag items](http://www.foodcritic.io/#FC086), which was previously skipped. 

## Why

Violation of this rule caused issues when attempting to implement [chef-vault](https://github.com/chef/chef-vault).

2019-01-10 01:05 UTC, jazaval approved these changes
Looks good, thanks!

2019-01-10 18:50 UTC, ehanlon requested changes

2019-01-10 18:50 UTC, ehanlon commented on recipes/bootstrap.rb
> +auth_data = data_bag_item node['vsts_agent']['data_bag'], node['vsts_agent']['data_bag_item']
Could we make this recipe a little more flexible by allowing a node attribute for Test Kitchen, and then a `chef_vault_item` for production?

```suggestion
auth_data = node['vsts_agent']['pat'] ? node['vsts_agent']['pat'] : chef_vault_item node['vsts_agent']['data_bag'], node['vsts_agent']['data_bag_item']
```

We would need to depend on `chef-vault` in order to get the `chef_vault_item` helper, and update the `kitchen.yml` to interpolate environment variables to override the attribute. 

A benefit of the `chef_vault_item` helper is the fallback mechanism to `data_bag_item`.

2019-01-12 04:26 UTC, ehanlon approved these changes

2019-01-14 19:26 UTC, merged